<a href="https://colab.research.google.com/github/geneciSI/colab/blob/main/AvaliaAna_01_BasesdeDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Bases de Dados (parte 1)

```
(*) Adaptado de material preparado pela Profa. Cristiane Sato
```

## Bibliotecas de Software

A linguagem _Python_, como outras linguagens ou ambientes de programação, possuem diversas bibliotecas de software.

Bibliotecas (de funções) são repositórios onde são armazenados comandos, operações ou instruções, que alguém criou e podemos utilizar sem ter que programar novamente.

Da mesma forma que muitas vezes recorremos às nossas bibliotecas (de livros) para consultar ou relembrar coisas, podemos usar as bibliotecas de software como as do Python.

Quando vamos buscar um livro na biblioteca precisamos saber o seu título para encontrá-lo. Em Python, também precisamos saber o nome da biblioteca que queremos usar.

Um sinônimo para biblioteca de software é o termo "pacote".

Vamos então, conhecer a biblioteca ou pacote _Pandas_.

## Biblioteca Pandas

_Pandas_ é uma biblioteca de software criada para a linguagem Python para manipulação e análise de dados. Em particular, oferece estruturas e operações para manipular tabelas.

Por exemplo, se precisamos usar um arquivo que temos gravado para mostrar os dados ou ordenar os dados, a biblioteca _Pandas_ possui instruções "prontas" para isso. Nós precisamos então, aprender como usá-las.

## Importanto a biblioteca pandas

O primeiro passo para utilizar uma biblioteca (pacote) é importar.
Imagine que esses pacotes são "externos" ao Python e precisamos importar, ou seja, trazê-los para dentro.

O comando _import_ do Python permite importar bibliotecas (pacotes).

A instrução a seguir importa o pacote pandas.

In [ ]:
import pandas as pd

```pd``` é o "apelido" que demos para o pandas. Podíamos escolher outro apelido!

Para acessar qualquer instrução da bibloteca que importamos teremos que usar o seu nome. Isso porque, podemos ter mais de uma biblioteca carregada.

Assim, um apelido (mais curto) ajuda na manipulação, ou seja, daqui pra frente ao invés de usar o termo  _pandas_ para acessar as instruções desta biblioteca usaremos apenas ```pd```.

## Carregando um arquivo CSV

Considere que precisamos processar os dados presentes no arquivo `filmes.csv`, ou seja, visualizar, fazer consultas, cálculos, etc.

Clicando no link abaixo você pode ter uma visão dos dados do arquivo `notas.csv`. Note que o caracter ";" separa os dados de cada coluna.

https://drive.google.com/file/d/1_eLlpyL_CrQ053JcSoEHQ4SdowPJG0iQ/view?usp=sharing

Para processarmos dados em um computador, precisamos trazer (carregar) esses dados para a **memória** do computador.

Estes dados geralmente estão gravados em algum lugar (disco, pen-drive, ou na nuvem). Por exemplo, o arquivo acima (`notas.csv`) está armazenado na nuvem, em uma pasta do google drive.

O primeiro passo para manipular os dados de um arquivo de dados é "abrir" este arquivo. Por exemplo, carregamos um documento, num editor de texto, usando a opção "abrir arquivo".

O processo de "abrir um arquivo" é também conhecido como "ler um arquivo", ou seja, ordenamos ao computador "leia os dados que estão gravados". Neste caso, "ler um arquivo" é o similar a "carregar os dados para a memória do computador.

_Pandas_ possui uma função para ler  (abrir um arquivo) que está gravado em algum lugar, seja no seu computador ou em algum lugar da "nuvem". A instrução **`read_csv`** abre e lê (carrega para a memória) um arquivo do tipo `CSV`.

A instrução a seguir abre o arquivo notas.csv

`pd.read_csv("notas.csv")`

Note que usamos _pd_ antes de _read.csv_. Isto é necessário pois _read_csv é uma instrução (função) que faz parte da biblioteca _pandas_ que carregamos.

Entre parênteses informamos o **nome do arquivo** que queremos abrir.

Caso o arquivo utilize um separador (dos atributos) que seja diferente de vírgula, precisamos adicionar o parâmetro `sep`, conforme instrução a seguir:

`pd.read_csv(notas.csv", sep = ";")`

Não vamos tentar executar a instrução acima, pois estamos usando este `notebook ` na "nuvem" (na internet). Ou seja, não temos o arquivo `notas.csv` localmente, mas podemos acessá-lo diretamente na nuvem.

Note que na instrução da próxima célula, informamos o _link_ do arquivo que está gravado em uma pasta do "google drive".

Mais adiante explicaremos melhor como obter esse _link_ do arquivo.

Note que além do _link_ do arquivo a ser aberto, usamos também o parâmetro `sep = ";"`. Isto foi necessário porque as colunas (atributos) do arquivo estão separados por ";" e não por ",". Se o separador for uma "," podemos omitir esse parâmetro `sep = ";"`.

Execute a célula abaixo para ver o conteúdo do arquivo (uma tabela ou planilha).

**Atenção!** É importante que você tenha executado (*play*) a célula anterior para importar a biblioteca pandas. Se não fez isso, ao tentar executar a célula a seguir aparecerá uma mensagem de erro.

In [ ]:
import pandas as pd
# a instrução a seguir monta o nome do arquivo no google drive
#https://drive.google.com/file/d/1_eLlpyL_CrQ053JcSoEHQ4SdowPJG0iQ/view?usp=sharing
codigo = "1_eLlpyL_CrQ053JcSoEHQ4SdowPJG0iQ"
file = "https://drive.google.com/u/3/uc?id=" + codigo + "&export=download"
# Base de Dados de Notas (de um curso)
# Note a especificação de SEPARADOR (ponto e vírgula)
curso = pd.read_csv(file, sep = ";")
# a instrução abaixo mostra os dados
curso

    Aluno Sexo  NotaPre  NotaPos
0   David    M       40       35
1     Ana    F       25       30
2   Ester    F       45       50
3   Bento    M       20       30
4    Caio    M       55       65
5  Helena    F       60       70
6   Jonas    M       65       75
7   Kelly    F       70       80
8    Fred    M       50       75
9   Gilda    F       55       85

Note que a **tabela** acima possui **quatro colunas** (ou atributos): Aluno (nome), Sexo, NotaPre e NotaPos. A primeira coluna exibida (0 a 9) é a numeração das linhas, ou seja, não faz parte dos dados.

### Dataframe e Variáveis

Para que possamos manipular a tabela (planilha) que foi aberta, ou seja, carregada para a memória, precisamos fazer uso de uma variável.

De forma simplista, uma variável, é uma região de memória que armazena dados temporariamente. Em _Python_ a forma da variável (tamanho, valores, etc) depende do que atribuímos a ela. O fato é que uma variável precisa ter um nome.

A instrução a seguir, armazena o resultado da "abertura e leitura do arquivo CSV" em uma variável chamada `df` (poderia ser outro nome):

`curso = pd.read_csv(file, sep = ";")`

Escolhemos o nome `curso` porque é nome que representa os dados armazenados (dados de um curso).

**DataFrame** é uma estrutura de dados bidimensional com os dados alinhados de forma tabular em linhas e colunas.
Mas isso é só uma informação adicional. Fique tranquilo(a).

A instrução a seguir, exibe os dados do "curso" na tela.

In [ ]:
curso

    Aluno Sexo  NotaPre  NotaPos
0   David    M       40       35
1     Ana    F       25       30
2   Ester    F       45       50
3   Bento    M       20       30
4    Caio    M       55       65
5  Helena    F       60       70
6   Jonas    M       65       75
7   Kelly    F       70       80
8    Fred    M       50       75
9   Gilda    F       55       85

Outra opção é usar o comando _print_ conforme abaixo.
Mais adiante veremso que o _print_ será obrigatório para visualizar os resultados em outros ambientes (que não o Colab).

Execute a célula a seguir.

In [ ]:
print(curso)

    Aluno Sexo  NotaPre  NotaPos
0   David    M       40       35
1     Ana    F       25       30
2   Ester    F       45       50
3   Bento    M       20       30
4    Caio    M       55       65
5  Helena    F       60       70
6   Jonas    M       65       75
7   Kelly    F       70       80
8    Fred    M       50       75
9   Gilda    F       55       85

## Conhecendo os dados

Para uma manipulação adequada da base de dados é importante conhecer algumas informações:
* Quantas linhas e colunas existem na tabela (dataframe)? `(shape)`
* Quais são as colunas (atributos) presentes na tabela? `(columns)`
* Quais as informações gerais da tabela? (`info()`)
* Existem atributos com dados nulos (ausência de informação)? `(count())`

In [ ]:
#Quantidade de linhas e colunas do DataFrame
curso.shape

(10, 4)

In [ ]:
#Colunas presentes no DataFrame
curso.columns

Index(['Aluno', 'Sexo', 'NotaPre', 'NotaPos'], dtype='object')

In [ ]:
curso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Aluno    10 non-null     object
 1   Sexo     10 non-null     object
 2   NotaPre  10 non-null     int64
 3   NotaPos  10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 448.0+ bytes

In [ ]:
#Quantas linhas com dados (não nulos) existem na tabela para cada atributo
curso.count()

Aluno      10
Sexo       10
NotaPre    10
NotaPos    10
dtype: int64

Note que cada atributo tem exatamente a quantidade = 10. Como a tabela tem exatamente 10 linhas (10 _entries_) pode-se afirmar que nenhuma coluna tem dados "vazios" (ausência de valores).

In [ ]:
# Alternativamente podemos somar os atributos isnull (valores vazios)
curso.isnull().sum()

Aluno      0
Sexo       0
NotaPre    0
NotaPos    0
dtype: int64

A função `describe` apresenta um resumo geral dos valores dos atributos numéricos (quantidade, média, desvio padrão, menor valor, maior valor, etc)

In [ ]:
curso.describe()

         NotaPre    NotaPos
count  10.000000  10.000000
mean   48.500000  59.500000
std    16.338435  21.402232
min    20.000000  30.000000
25%    41.250000  38.750000
50%    52.500000  67.500000
75%    58.750000  75.000000
max    70.000000  85.000000